language: ruby

os: linux

dist: bionic

cache:
  bundler: true
  pip: true

rvm:
  - 2.7
  - 2.6
  - 2.5

jobs:
  fast_finish: true

if: type != pull_request || head_repo != repo

before_install:
  - gem update -N --system
  - gem install -N bundler
  - pip3 install syntrax blockdiag seqdiag actdiag nwdiag
  - npm install --global yarn
  - yarn global add bit-field mermaid.cli netlistsvg nomnoml state-machine-cat vega-cli vega-lite wavedrom-cli

install: bundle install --jobs 4 --retry 3

script: bundle exec rake features

addons:
  apt:
    update: true
    packages:
      - graphviz
      - npm
      - libgif-dev
      - libpango1.0-dev
      - node-gyp
      - python3-pip
      - python3-setuptools
      - python3-cairo
      - python3-gi-cairo
